// TempControl.idl
module org {
    module hasselman {
        module dds {
            module sensors {
                module temperature {

                    enum TemperatureScale {
                        CELSIUS,
                        FAHRENHEIT,
                        KELVIN
                    };

                    struct TemperatureSensorType {
                        short id;
                        float temperature;
                        float humidity;
                        TemperatureScale scale;
                    };

                    #pragma keylist TemperatureSensorType id
                };

                module contact {
                    enum Status {
                        OK,
                        MAINTENANCE_REQUIRED
                    };

                    enum Type {
                        DOOR,
                        WINDOW
                    };

                    struct ContactSensorType {
                        string id;
                        Type type;
                        boolean isOpen;
                        Status status;
                        short batteryPercentage;
                    };

                    #pragma keylist ContactSensorType id
                };

            };
        };
    };
};

